# Generated by Django 4.1.4 on 2023-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compiler", "0002_alter_user_departments_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_responsive_for_paper",
            field=models.ManyToManyField(
                blank=True,
                related_name="Paper_for_responsive_department",
                to="compiler.paper",
            ),
        ),
    ]
