# Generated by Django 4.1.4 on 2023-05-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_department_paper_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
