# Generated by Django 4.1.4 on 2023-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_department_options_alter_paper_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_name',
            field=models.CharField(max_length=50, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_department',
            field=models.IntegerField(verbose_name='Отдел пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
