# Generated by Django 4.1.4 on 2023-05-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.department'),
        ),
    ]
