# Generated by Django 4.1.4 on 2023-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_alter_user_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Является админом?'),
        ),
    ]
