# Generated by Django 4.1.4 on 2023-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_department',
            new_name='user_departments',
        ),
        migrations.AddField(
            model_name='user',
            name='user_papers',
            field=models.ManyToManyField(to='compiler.paper'),
        ),
    ]
