# Generated by Django 4.1.4 on 2023-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0008_rename_user_department_user_user_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_departments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_papers',
        ),
        migrations.AddField(
            model_name='user',
            name='departments_employee',
            field=models.ManyToManyField(related_name='users_emplyee', to='compiler.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='departments_representative',
            field=models.ManyToManyField(related_name='users_representative', to='compiler.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='papers_of_user',
            field=models.ManyToManyField(related_name='users_of_paper', to='compiler.paper'),
        ),
    ]
